### ISSUE TITLE
cljdoc build failing because release.clj seems to be included in jar

### ISSUE THREAD

**Issue by martinklepsch** [appliedsciencestudio/js-interop#1]
Logs: https://circleci.com/gh/cljdoc/builder/2302

There's [documentation for running cljdoc locally](https://cljdoc.org/d/cljdoc/cljdoc/0.0.1315-c9e9a7e/doc/running-cljdoc-locally) but if you want I can also try to find some time and make things work.

**Comment by mhuebert** [comment]
Thanks for checking in! This was a relatively simple fix - moved some things into appropriate `:alias` source-paths. It now builds fine: https://cljdoc.org/d/appliedscience/js-interop/0.1.7/doc/readme
