### ISSUE TITLE
Support for CLJC

### ISSUE THREAD

**Issue by den1k** [appliedsciencestudio/js-interop#14]
Hey Matt 👋️

I often use `js-interop` in `.cljc` files. These files are mostly front-end UI component files in CLJC to support SSR. The UI components have lifecycle methods defined that only run in js-land. However, because we're dealing with CLJC I find myself having to wrap requires and every call with `#?(:cljs ...)` reader conditionals. This gets ugly quickly.

Any ideas how to get around this?

I like Roman's approach in UIX, where he implemented either no-op or analog function in `clj`
https://github.com/roman01la/uix/blob/master/core/src/uix/core/alpha.cljc#L271-L280

**Comment by mhuebert** [comment]
hello! nice to see you here :). 

'tis a good question... I've run into similar issues in my own work. Made a PR to experiment with the no-op route... https://github.com/appliedsciencestudio/js-interop/pull/15
