### ISSUE TITLE
Call a function in a nested key?

### ISSUE THREAD

**Issue by viebel** [appliedsciencestudio/js-interop#5]
I have a javacript object name myObj that looks like this:
```js
{
  foo: 
      { bar: x => x }
}
```

And I want to call `myObj.foo.bar(42)`.

How can I do that with `js-interop`?

**Comment by mhuebert** [comment]
Something like this should work,
```clj
(-> (j/get myObj :foo) 
    (j/call :bar 42))
```

**Comment by mhuebert** [comment]
I thought about adding something like `call-in`, eg
```
(j/call-in myObj [:foo :bar] 42)
```
I wasn’t sure if there would be demand for it

**Comment by viebel** [comment]
`j/call-in` would be awesome!

**Comment by jackrusher** [comment]
I, too, endorse `j/call-in`.

**Comment by mhuebert** [comment]
@viebel @jackrusher I've just added `j/call-in` and `j/apply-in`. I haven't cut a release yet, but you can give it a try with deps using the latest sha: 
```
{:git/url "https://github.com/appliedsciencestudio/js-interop.git" 
 :sha "43168deb16122965da08f525f8774c30b04cfcc8"}
```

There are a couple of tests here: https://github.com/appliedsciencestudio/js-interop/blob/43168deb16122965da08f525f8774c30b04cfcc8/src/test/applied_science/js_interop_test.cljs#L260-L275

**Comment by viebel** [comment]
It works like a charm @mhuebert.
Thank you!

**Comment by viebel** [comment]
@mhuebert Can you cut a release with `call-in`. One of my projects use leiningen.

**Comment by mhuebert** [comment]
@viebel sure thing, I've just pushed `0.1.14`

**Comment by viebel** [comment]
Thanks a lot @mhuebert 
It might be useful to update the README with the added functions

**Comment by jackrusher** [comment]
@viebel this sounds like a great idea and a great opportunity for you to contribute with a pull request containing that update :)
