### ISSUE TITLE
compile error with `j/lit` and fn value

### ISSUE THREAD

**Issue by mk** [appliedsciencestudio/js-interop#9]
The following code produces a compile error `Parameter declaration cljs.core/array should be a vector` as it's trying to convert the argument vector into a js array:
```clojure
(require '[applied-science.js-interop :as j])
(j/lit {:key (fn [])})
```

**Comment by mhuebert** [comment]
Thanks for the report. I think we should modify `j/lit` to stop traversing downward when lists are encountered, so that values of objects or arrays can be clojure expressions.

**Comment by mk** [comment]
Sounds good, I’ll see if I can come up with a PR tomorrow.
